name: Generate ASCII Artwork

on:
 push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List Repo Files
              run: ls -ltra
              
            - name: adding permission to file
              run: chmod +x ascii-script.sh

            - name: Executing Shell script
              run: ./ascii-script.sh
